//
// all.h - A single include file for all the functions.
//
#ifndef CSYNTH_FUNC_ALL_H
#define CSYNTH_FUNC_ALL_H

#include "./comp/comp.h"
#include "./comp/comps.h"
#include "./effect/continuous.h"
#include "./effect/delay.h"
#include "./effect/effects.h"
#include "./effect/loop.h"
#include "./effect/press.h"
#include "./effect/reverb.h"
#include "./envelope/adsr.h"
#include "./envelope/envelopes.h"
#include "./envelope/smooth.h"
#include "./envelope/step.h"
#include "./filter/chorus.h"
#include "./filter/filters.h"
#include "./filter/high_pass.h"
#include "./filter/limit.h"
#include "./filter/low_pass.h"
#include "./filter/resonant.h"
#include "./gen/const.h"
#include "./gen/gauss.h"
#include "./gen/gens.h"
#include "./gen/karplus_strong.h"
#include "./gen/notes.h"
#include "./gen/saw.h"
#include "./gen/sine.h"
#include "./gen/square.h"
#include "./gen/timer.h"
#include "./gen/triangle.h"
#include "./gen/uniform.h"
#include "./op/add.h"
#include "./op/inv.h"
#include "./op/max.h"
#include "./op/min.h"
#include "./op/mul.h"
#include "./op/neg.h"
#include "./op/ops.h"
#include "./op/pow.h"
#include "./op/sin.h"
#include "./util/callback.h"
#include "./util/logger.h"
#include "./util/print.h"

#endif // CSYNTH_FUNC_ALL_H
