#!/bin/bash

set -e

if [ $# -eq 0 ]; then
    pattern=".*\\.h"
fi

if [ $# -eq 1 ]; then
    pattern=".*$1.*\\.h"
fi

rm -f ./tests/test.c

find ./tests -regex "$pattern" -print0 | while read -d $'\0' file; do
    name=$(basename "$file" .h)
    printf "#include \".$file\"\\nint main() { test_$name(); return 0; }" > ./tests/test.c
    gcc ./tests/test.c -o bin/test -Wall -Wextra -lm
    ./bin/test
    echo -n "."
done


if [ -f ./tests/test.c ]; then
    rm ./tests/test.c
    printf "\r\e[KAll tests passed\n"
else
    echo "No tests found for pattern: $1"
    exit -1
fi
